<?php

namespace VZenix\Bundle\ContactBundle\Entity;

use Doctrine\ORM\Mapping AS ORM;

/**
 * Entity for contact form logger
 * @ORM\Entity @ORM\Table(name="contact_log")
 * @author Francisco Muros Espadas <paco@vzenix.es>
 */
class ContactEntity
{

    /**
     * Primary key for index
     * @var int
     * @ORM\Id @ORM\Column(type="integer") @ORM\GeneratedValue
     */
    public $id;

    /**
     * Default timezone is UTC, date of creation
     * @var \DateTime
     * @ORM\Column(type="datetime") 
     */
    public $date;

    /**
     * Personal name
     * @var string
     * @ORM\Column(type="string")
     */
    public $name;

    /**
     * Email for contact
     * @var string
     * @ORM\Column(type="string")
     */
    public $email;

    /**
     * message
     * @var string
     * @ORM\Column(type="text")
     */
    public $message;

    /**
     * Constructor of entity
     */
    public function __construct()
    {
        $this->date = new \DateTime("now");
        $this->date->setTimezone(new \DateTimeZone("UTC"));
    }

    /**
     * Autogenerated ID
     * @return string
     */
    public function getID(): int
    {
        return (int) $this->id;
    }

    /**
     * Date of creation
     * @return string
     */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * Name
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Mail
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * message
     * @return string
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Set the name
     * @param string $name
     */
    public function setName(string $name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Set the email
     * @param string $email
     */
    public function setEmail(string $email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Set message
     * @param string $message
     */
    public function setMessage(string $message)
    {
        $this->message = $message;
        return $this;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return ContactEntity
     */
    public function setDate($date)
    {
        $this->date = $date;
        return $this;
    }

}
